# Generated by Django 5.1.5 on 2025-01-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AuctionApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trades",
            name="ContactInfo",
            field=models.CharField(default="", max_length=25),
        ),
    ]
